# Minimal Hacker âš«ğŸ‘¨â€ğŸ’»
format = """$directory$git_branch$character """

add_newline = false

[directory]
style = "bold dimmed white"
format = "[$path]($style)"

[git_branch]
symbol = "î‚ "
style = "dimmed green"
format = " [$symbol $branch]($style)"

[character]
success_symbol = "[#](bold white)"
error_symbol = "[!](bold red)"
vicmd_symbol = "[<](bold yellow)"

